services:
  - type: web
    name: backend-service
    runtime: node
    rootDirectory: web/backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
    plan: free