/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/j3ROUP98UtM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"

export default function PickupPage() {
  return (
    (<div >
     
      <div className="flex flex-col">
       
        <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
          <Card className="w-full">
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Student Pickup Log</CardTitle>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Student</TableHead>
                    <TableHead>Parent</TableHead>
                    <TableHead>Arrived</TableHead>
                    <TableHead>Time</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell className="font-medium">John Doe</TableCell>
                    <TableCell>Jane Doe</TableCell>
                    <TableCell>
                      <Badge variant="success">Yes</Badge>
                    </TableCell>
                    <TableCell>3:25 PM</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Jane Smith</TableCell>
                    <TableCell>John Smith</TableCell>
                    <TableCell>
                      <Badge variant="success">Yes</Badge>
                    </TableCell>
                    <TableCell>3:18 PM</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Michael Lee</TableCell>
                    <TableCell>Sarah Lee</TableCell>
                    <TableCell>
                      <Badge variant="danger">No</Badge>
                    </TableCell>
                    <TableCell>3:35 PM</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Emily Chen</TableCell>
                    <TableCell>David Chen</TableCell>
                    <TableCell>
                      <Badge variant="success">Yes</Badge>
                    </TableCell>
                    <TableCell>3:40 PM</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Ethan Park</TableCell>
                    <TableCell>Sophia Park</TableCell>
                    <TableCell>
                      <Badge variant="danger">No</Badge>
                    </TableCell>
                    <TableCell>3:45 PM</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Olivia Davis</TableCell>
                    <TableCell>Michael Davis</TableCell>
                    <TableCell>
                      <Badge variant="success">Yes</Badge>
                    </TableCell>
                    <TableCell>3:50 PM</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Lucas Gonzalez</TableCell>
                    <TableCell>Isabella Gonzalez</TableCell>
                    <TableCell>
                      <Badge variant="danger">No</Badge>
                    </TableCell>
                    <TableCell>3:55 PM</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Sophia Ramirez</TableCell>
                    <TableCell>Daniel Ramirez</TableCell>
                    <TableCell>
                      <Badge variant="success">Yes</Badge>
                    </TableCell>
                    <TableCell>4:00 PM</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Liam Hernandez</TableCell>
                    <TableCell>Mia Hernandez</TableCell>
                    <TableCell>
                      <Badge variant="danger">No</Badge>
                    </TableCell>
                    <TableCell>4:05 PM</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Isabella Diaz</TableCell>
                    <TableCell>Lucas Diaz</TableCell>
                    <TableCell>
                      <Badge variant="success">Yes</Badge>
                    </TableCell>
                    <TableCell>4:10 PM</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </main>
      </div>
    </div>)
  );
}

function BellIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>)
  );
}


function CarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2" />
      <circle cx="7" cy="17" r="2" />
      <path d="M9 17h6" />
      <circle cx="17" cy="17" r="2" />
    </svg>)
  );
}


function LayoutDashboardIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="7" height="9" x="3" y="3" rx="1" />
      <rect width="7" height="5" x="14" y="3" rx="1" />
      <rect width="7" height="9" x="14" y="12" rx="1" />
      <rect width="7" height="5" x="3" y="16" rx="1" />
    </svg>)
  );
}


function MegaphoneIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 11 18-5v12L3 14v-3z" />
      <path d="M11.6 16.8a3 3 0 1 1-5.8-1.6" />
    </svg>)
  );
}


function SchoolIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M14 22v-4a2 2 0 1 0-4 0v4" />
      <path d="m18 10 4 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-8l4-2" />
      <path d="M18 5v17" />
      <path d="m4 6 8-4 8 4" />
      <path d="M6 5v17" />
      <circle cx="12" cy="9" r="2" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}
