// layout.jsx
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/component/Nav";
import SearchBar from "@/components/component/SearchBar";
import { NotificationProvider } from "@/components/component/NotificationProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body key="1" className="grid min-h-screen w-full grid-cols-[280px_1fr]">
        <NotificationProvider>
          <Nav />
          <main>{children}</main>
        </NotificationProvider>
      </body>
    </html>
  );
}
