import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/component/Nav";
import SearchBar from "@/components/component/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body key="1" className="grid min-h-screen w-full grid-cols-[280px_1fr]">
        <Nav />
        <main >
          {/* <SearchBar /> */}
          {children} {/* This is where the content of each page will go */}
        </main>
      </body>
    </html>
  );
}
