/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jUIa9OcqVuT
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/jUIa9OcqVuT
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

"use client";
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import { Checkbox } from "antd";
import AnnouncementModal from "@/components/component/AnnoucementModal";
import {
  CalendarCheckIcon,
  CircleAlertIcon,
  MegaphoneIcon,
} from "@/public/icons/icons";

export default function Notifications() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [announcements, setAnnouncements] = useState([]);
  const [selectedAnnouncements, setSelectedAnnouncements] = useState([]);

  const formatDate = (dateString) => {
    const date = new Date(dateString);

    // Format: "October 5, 2023 at 2:30 PM"
    return date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "numeric",
      minute: "numeric",
      hour12: true,
    });
  };

  const getRelativeTime = (dateString) => {
    const date = new Date(dateString);
    const now = new Date();
    const diffInSeconds = Math.floor((now - date) / 1000);

    if (diffInSeconds < 60) {
      return "just now";
    } else if (diffInSeconds < 3600) {
      const minutes = Math.floor(diffInSeconds / 60);
      return `${minutes} ${minutes === 1 ? "minute" : "minutes"} ago`;
    } else if (diffInSeconds < 86400) {
      const hours = Math.floor(diffInSeconds / 3600);
      return `${hours} ${hours === 1 ? "hour" : "hours"} ago`;
    } else if (diffInSeconds < 604800) {
      const days = Math.floor(diffInSeconds / 86400);
      return `${days} ${days === 1 ? "day" : "days"} ago`;
    } else {
      return formatDate(date);
    }
  };

  const handleCreateAnnouncement = async (data) => {
    try {
      const response = await fetch("http://localhost:5000/api/notifications", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(data),
      });

      if (response.ok) {
        const newAnnouncement = await response.json();
        setAnnouncements((prevAnnouncements) => [
          ...prevAnnouncements,
          newAnnouncement,
        ]);
        setIsModalOpen(false);
        console.log("New Announcement:", newAnnouncement);
      } else {
        console.error("Error creating announcement:", response.statusText);
      }
    } catch (error) {
      console.error("Error creating announcement:", error);
    }
  };

  const handleDeleteSelected = async () => {
    try {
      const response = await fetch(
        "http://localhost:5000/api/notifications/bulk",
        {
          method: "DELETE",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ ids: selectedAnnouncements }),
        }
      );

      if (response.ok) {
        setAnnouncements((prevAnnouncements) =>
          prevAnnouncements.filter(
            (announcement) => !selectedAnnouncements.includes(announcement._id)
          )
        );
        setSelectedAnnouncements([]);
      } else {
        console.error("Error deleting announcements:", response.statusText);
      }
    } catch (error) {
      console.error("Error deleting announcements:", error);
    }
  };

  const handleSelectAll = (e) => {
    if (e.target.checked) {
      setSelectedAnnouncements(announcements.map((a) => a._id));
    } else {
      setSelectedAnnouncements([]);
    }
  };

  const handleSelectAnnouncement = (id) => {
    setSelectedAnnouncements((prev) => {
      if (prev.includes(id)) {
        return prev.filter((item) => item !== id);
      } else {
        return [...prev, id];
      }
    });
  };

  function getIcon(icon) {
    switch (icon) {
      case "calendar":
        return (
          <CalendarCheckIcon className="w-6 h-6 text-gray-700 dark:text-black" />
        );
      case "alert":
        return (
          <CircleAlertIcon className="w-6 h-6 text-gray-700 dark:text-black" />
        );
      case "megaphone":
        return (
          <MegaphoneIcon className="w-6 h-6 text-gray-700 dark:text-black" />
        );
      default:
        return (
          <CalendarCheckIcon className="w-6 h-6 text-gray-700 dark:text-black" />
        );
    }
  }

  useEffect(() => {
    const fetchAnnouncements = async () => {
      try {
        const response = await fetch("http://localhost:5000/api/notifications");
        if (response.ok) {
          const data = await response.json();
          setAnnouncements(data);
          console.log("Fetched announcements:", data);
        } else {
          console.error("Error fetching announcements:", response.statusText);
        }
      } catch (error) {
        console.error("Error fetching announcements:", error);
      }
    };

    fetchAnnouncements();
  }, []);

  return (
    <div>
      <div className="flex flex-col">
        <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
          <div className="flex items-center justify-between">
            <Card className="w-full">
              <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0 mb-4">
                <div className="flex items-center gap-4">
                  <CardTitle className="text-sm font-medium text-gray-900 dark:text-white">
                    Announcements
                  </CardTitle>
                  <Checkbox
                    checked={
                      selectedAnnouncements.length === announcements.length &&
                      announcements.length > 0
                    }
                    indeterminate={
                      selectedAnnouncements.length > 0 &&
                      selectedAnnouncements.length < announcements.length
                    }
                    onChange={handleSelectAll}
                  >
                    <span className="text-sm ml-2 text-gray-700 dark:text-gray-300">
                      Select All ({selectedAnnouncements.length}/
                      {announcements.length})
                    </span>
                  </Checkbox>
                </div>
                <div className="flex gap-2">
                  {selectedAnnouncements.length > 0 && (
                    <Button
                      className="bg-red-500 text-white hover:bg-red-600 transition-colors"
                      size="sm"
                      onClick={handleDeleteSelected}
                    >
                      Delete Selected
                    </Button>
                  )}
                  <Button
                    className="bg-black text-white hover:bg-gray-900 transition-colors"
                    size="sm"
                    onClick={() => setIsModalOpen(true)}
                  >
                    Create New Announcement
                  </Button>
                </div>
                <AnnouncementModal
                  open={isModalOpen}
                  onClose={() => setIsModalOpen(false)}
                  onSubmit={handleCreateAnnouncement}
                  className="dark:bg-gray-800"
                />
              </CardHeader>
              <CardContent>
                <div className="bg-white dark:bg-gray-900 p-6">
                  <div className="space-y-4">
                    {announcements.map((announcement) => (
                      <div
                        key={announcement.id}
                        className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4"
                      >
                        <div className="flex items-start">
                          <Checkbox
                            checked={selectedAnnouncements.includes(
                              announcement._id
                            )}
                            onChange={() =>
                              handleSelectAnnouncement(announcement._id)
                            }
                            className="mt-2 mr-4"
                          />
                          <div className="flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center">
                            {getIcon(announcement.icon)}
                          </div>
                          <div className="ml-4 flex-1">
                            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                              {announcement.title}
                            </h3>
                            <p className="text-gray-600 dark:text-gray-400 mt-1 text-sm">
                              {announcement.description}
                            </p>
                            <p className="text-gray-500 dark:text-gray-500 text-xs mt-2">
                              {getRelativeTime(announcement.createdAt)}
                            </p>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </main>
      </div>
    </div>
  );
}
